openapi: 3.1.0
info:
  title: Reorder types
  version: 1.0.0
paths:
  /example:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: [string, "null"]
