openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    get:
      parameters:
        - name: param1
          in: query
          style: spaceDelimited
          explode: true
          schema:
            type: array
            items:
              type: string
        - name: param2
          in: query
          style: spaceDelimited
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content: { }
