openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              type: array
              items:
                type: string
              xml:
                wrapped: true
      responses:
        '200':
          description: OK
          content: { }
