openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /pet:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                profileImage: {}
            encoding:
              profileImage:
                contentType: image/png
      responses:
        '200':
          description: OK
