openapi: 3.1.0
info:
  title: Add type to union
  version: 1.0.0
paths:
  /example:
    get:
      parameters:
        - name: data
          in: query
          required: false
          schema:
            type: [string, integer]  # Before - Union type with string and integer only
      responses:
        '200':
          description: OK
