openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    get:
      responses:
        '200':
          description: OK
          content: { }
          headers:
            X-Rate-Limit-Limit:
              schema:
                type: integer