openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              title: This is a title
              type: string
      responses:
        '200':
          description: OK
          content: { }
