openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /pet:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: OK
components:
  schemas:
    Pet:
      oneOf:
        - type: object
          properties:
            prop1:
              type: string
        - type: object
          properties:
            prop2:
              type: number
