openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /users:
    get:
      summary: Gets a list of users.
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  prop1:
                    type: object
                    properties:
                      prop11:
                        type: string
          description: 'desc'
