openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    get:
      parameters:
        - name: param1
          in: query
          description: It is a  NEW  param1 description.
          schema:
            type: string
      responses:
        '200':
          description: OK
          content: { }
