openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    get:
      externalDocs:
        description: External Docs
        url: https://example.com
      responses:
        '200':
          description: OK
          content: { }
