openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /users:
    get:
      summary: Gets a list of users.
      responses:
        '200':
          description: OK
          headers:
            XRateLimit:
              $ref: '#/components/headers/X-Rate-Limit'
components:
  headers:
    X-Rate-Limit:
      style: simple
      schema:
        type: integer
        description: Request limit
