openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /pet:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              title: Pet Schema
              type: object
              properties:
                prop1:
                  type: string
      responses:
        '200':
          description: OK
