openapi: 3.1.0
info:
  title: Reorder types
  version: 1.0.0
paths:
  /example:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: ["null", string]
      responses:
        '200':
          description: OK
