openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      parameters:
        - name: p1
          in: query
          schema:
            anyOf:
              - type: string
              - type: number
              - type: integer
              - type: boolean
              - type: array
                items: { }
              - type: object
      responses:
        '200':
          description: OK
          content: { }
