openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /users:
    get:
      summary: Gets a list of users.
      parameters:
        - in: query
          name: offset
          schema:
            type: object
            properties:
              prop1:
                type: object
                properties:
                  prop11:
                    anyOf:
                      - type: object
                        properties:
                          prop1:
                            type: string
                      - type: object
                        properties:
                          prop2:
                            type: number
      responses:
        '200':
          description: OK
