openapi: 3.1.0
info:
  title: Union type equivalent to anyOf
  version: 1.0.0
paths:
  /path1:
    post:
      parameters:
        - name: field1
          in: query
          schema:
            type: [string, integer]
      responses:
        '200':
          description: OK
