openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      parameters:
        - name: p1
          in: query
          schema:
            oneOf:
              - type: object
                properties:
                  prop1:
                    type: string
              - type: object
                properties:
                  prop2:
                    type: number
              - type: object
                properties:
                  prop3:
                    type: boolean
      responses:
        '200':
          description: OK
          content: { }
