openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      requestBody:
        description: This is description of request body
        content: { }
      responses:
        '200':
          description: OK
          content: { }
