openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A list of pets
          x-cacheable: false
