openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /pets:
    get:
      parameters:
        - name: param1
          in: query
          x-custom-prop: some value 2
          schema:
            type: string
      responses:
        '200':
          description: OK
