openapi: 3.1.0
info:
  title: Nullable equivalent to null
  version: 1.0.0
paths:
  /path1:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              type: [string, "null"]
      responses:
        '200':
          description: OK
          content: {}
