openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /pet:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              oneOf:
                - type: object
                  properties:
                    prop1:
                      type: string
                - type: object
                  properties:
                    prop2:
                      type: number
                - type: object
                  properties:
                    prop3:
                      type: string

      responses:
        '200':
          description: OK
