openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                id:
                  type: integer
              xml:
                prefix: 'p1'
                namespace: 'http://example.com/schema'
      responses:
        '200':
          description: OK
          content: { }
