openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    get:
      parameters:
        - name: param1
          in: path
          schema:
            type: string
        - name: param2
          in: path
          allowEmptyValue: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content: { }
