openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      parameters:
        - name: p1
          in: query
          schema:
            type: object
            properties:
              id:
                type: integer
                xml:
                  name: 'xml-id-2'
      responses:
        '200':
          description: OK
          content: { }
