openapi: 3.1.0
info:
  title: Change to union type
  version: 1.0.0
paths:
  /example:
    get:
      parameters:
        - name: input
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
