openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      parameters:
        - name: p1
          in: query
          schema:
            properties:
              option1:
                type: string
                readOnly: false
              option2:
                type: string
      responses:
        '200':
          description: OK
          content: { }
