openapi: 3.1.0
info:
  title: Add type to union
  version: 1.0.0
paths:
  /example:
    get:
      responses:
        '200':
          description: OK
          headers:
            X-Header-1:
              schema:
                type: [string, integer]