openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /pet:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                profileImage: {}
            encoding:
              profileImage:
                contentType: image/png
                headers:
                  X-Rate-Limit-Limit:
                    description: The number of allowed requests in the current period
                    schema:
                      type: integer
      responses:
        '200':
          description: OK
