openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /users:
    get:
      summary: Gets a list of users.
      parameters:
        - in: query
          name: offset
          style: simple
          schema:
            type: integer
      responses:
        '200':
          description: OK
