openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      parameters:
        - name: p1
          in: query
          schema:
            properties:
              option1:
                minProperties: 0
                properties:
                  prop1:
                    type: string
              option2:
                properties:
                  prop1:
                    type: string
      responses:
        '200':
          description: OK
          content: { }
