openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    get:
      servers:
        - url: https://example.com
          description: It is a description of server
      responses:
        '200':
          description: OK
          content: { }
