openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      parameters:
        - name: p1
          in: query
          schema:
            type: object
            required:
              - prop1
              - prop2
            properties:
              prop1:
                type: string
              prop2:
                type: number
      responses:
        '200':
          description: OK
          content: { }
