openapi: 3.0.3
info:
  title: test
  version: 0.1.0
paths:
  /path1:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              type: string
            examples:
              example1:
                value: name
                externalValue: 'https://example.org/examples/address-example.xml'
      responses:
        '200':
          description: OK
          content: { }
